### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by sylveawong**
Added Bugsnag

### CODE REVIEW

**Comment by jmshal** [comment]
:+1:

**Comment by nikmd23** [comment]
Hi @sylveawong! Thanks so much for sending this in, Bugsnag looks great.

Can I get you to make one change to this PR? Can you change the perk URL to point to a page where Bugsnag actually says they are free for open source? It looks like they have done so [on their blog](https://bugsnag.com/blog/bugsnag-loves-open-source). Just update to that URL and I'll gladly accept this and send out a tweet on the ossperks twitter account.

PS - Congrats on your new job!

**Comment by jessicard** [comment]
Yay, this looks ready to go! Thanks @nikmd23

**Comment by nikmd23** [comment]
Thanks for helping to get this finished off @jessicard

**Pull request merged**
