### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by dannycabrera**
Added Telerik JustDecompile & Fiddler.

### CODE REVIEW

**Comment by bdukes** [comment]
These are just freeware, right?  They aren't perks specific to OSS devs.

**Comment by dannycabrera** [comment]
Correct they are free tools. Is the list supposed to contain only ones targeting OSS?

**Comment by bdukes** [comment]
Yeah, see the last note at the bottom of the readme

**Comment by dannycabrera** [comment]
Not fair! That line was added 19hrs ago :) My confusion comes from seeing dotPeek, how is that a perk and not Telerik's JustDecompile?

**Comment by bdukes** [comment]
Good catch.  I've submitted a request to remove dotPeek: https://github.com/nikmd23/ossperks/pull/23

**Comment by nikmd23** [comment]
Thanks for showing so much care in making ossPerks a great list @dannycabrera and @bdukes.

@bdukes is right, freeware should not be on the list - it would just get out of hand. That's always been a rule, but I forgot to state it until I updated the readme yesterday. (In fact, Fiddler was listed at one point and removed later.)

I'm going to close this pull request and I'll accept @bdukes to remove dotPeek.

**Comment by dannycabrera** [comment]
Thanks guys

**Pull request closed without merging**
