### PR TITLE
Added some more Red Gate tools, and updated some Platform tags

### PR DESCRIPTION
**Pull request by camassey**
A few of the new tools don't have "official" blog posts associated with them to announce that they're free to OSS, but they're internally in that bucket (and the sales teams know that). Do we need to puts some clear public information anywhere?

### CODE REVIEW

**Comment by nikmd23** [comment]
@camassey - a public statement to link to would really be best.

Either what or a mention on the product pages. Something like "Need this for an OSS project, just do XYZ".

I'm not very picky - but having a URL means that I can just do a 404 scan on ossperks.com to find products that no longer offer the perk.

**Comment by camassey** [comment]
No problem. I’ll get something set up and update once there’s some public info!

**Comment by camassey** [comment]
Added the appropriate URL - let me know if you think we need anything else.

**Comment by nikmd23** [comment]
Looks good to me!

**Pull request merged**
