### PR TITLE
Added dotPeek and Fiddler

### PR DESCRIPTION
**Pull request by maartenba**

### CODE REVIEW

**Comment by avanderhoorn** [comment]
Are you able to fix this up so we can pull it in?

**Comment by maartenba** [comment]
Me?

**Comment by avanderhoorn** [comment]
Ya, PR can't be brought in atm.

**Comment by maartenba** [comment]
That’s sort of strange… Replaying changes and sending the PR again.

**Comment by avanderhoorn** [comment]
Thanks!

**Pull request closed without merging**
