### PR TITLE
Add CodeBetter CI

### PR DESCRIPTION
**Pull request by bdukes**

### CODE REVIEW

**Comment by nikmd23** [comment]
@bdukes - TeamCity is listed already. I propose that we replace the current link to your link (which is where it should have gone all along)

Do you want to just update this PR?

**Comment by bdukes** [comment]
I would think that they've two separate things.  The ability to have your own unlimited TeamCity license is a very different thing (IMO) to having access to a hosted TeamCity instance.

**Comment by nikmd23** [comment]
That's a good point. I always thought/assumed that the perk listed was CodeBetter - but there might be two different perks.

@maartenba can you clear this up?

**Comment by maartenba** [comment]
CodeBetter is indeed a separate thing, hosting TeamCity for OSS

Sent from my Windows Phone

**Comment by nikmd23** [comment]
Thanks for the clarification @maartenba.

I've updated the original TeamCity listing to point to a more appropriate URL and merged in @bdukes changes.

Thanks @bdukes!

**Pull request merged**
