### PR TITLE
Add PostSharp

### PR DESCRIPTION
**Pull request by bdukes**

### CODE REVIEW

**Comment by nikmd23** [comment]
Thanks again @bdukes! You're the best.

**Comment by nikmd23** [comment]
Hey @bdukes, as I look more into this, it doesn't seem like this is an OSS Perk. I looks to me like they just happen to have a freemium model.

Am I missing something?

**Comment by bdukes** [comment]
In the discounts section at the bottom of the pricing page, the top right discount is

> Open-Source Projects
> 
> Free use and redistribution
> of PostSharp for qualified open-source projects.

As I understand it, this includes the ability to used the for-pay components in an OSS project.

**Comment by nikmd23** [comment]
Okay, I didn't see that! Fair enough.

I think they could do a better job being clear about that - but I'm good with what they have.

**Pull request merged**
