### PR TITLE
Added Octopus Deploy

### PR DESCRIPTION
**Pull request by RobGibbens**
With correct link to license this time.

### CODE REVIEW

**Comment by nikmd23** [comment]
Hey @RobGibbens,

Can you fix this pull request so that we can automatically merge it? Should be good to go after that.

**Comment by RobGibbens** [comment]
What needs to be fixed?

**Comment by nikmd23** [comment]
Hey @RobGibbens,

I totally dropped the ball on pulling this in! :frowning:

Since you've submitted this I've switched the site over to Jekyll, so your commits won't come in cleanly anymore. But don't worry - I'm going to get them in manually!

I've already "ported" your RavenDB change in commit 88611785adde9cbf71424c9059d8172fc406d005 - and it is now live. 

Your Octopus Deploy change will be ported over today too. I just have to figure out how to deal with the `<br/>` you have in the description in [YAML](http://www.yaml.org/).

Once I get that live I'll close this pull request.

**Comment by nikmd23** [comment]
I've added in the Octopus Deploy change now too - d46df11bccbd83b6b4d682e154d286dc3502bae6.

Thanks for your contribution and patience @RobGibbens!

**Pull request closed without merging**
